# iw配置
iw:
  dao:
    data-permission:
      enabled: true
      enable-table-names:
        - eat_meal

# 服务器配置
server:
  servlet:
    context-path: /eat-service
  port: 18003

# spring 配置
spring:
  application:
    name: iw-eat-service
  datasource:
    driver-class-name: ${iw.db.driver-class}
    url: ${iw.db.url}
    username: ${iw.db.username}
    password: ${iw.db.password}
  config:
    import:
     - optional:nacos:iw-web
     - optional:nacos:${spring.application.name}.yml
  cloud:
    nacos:
      discovery:
        enabled: true
      config:
        file-extension: yaml
      password: ${SPRING_CLOUD_NACOS_PASSWORD:}
      username: ${SPRING_CLOUD_NACOS_USERNAME:}
      server-addr: ${SPRING_CLOUD_NACOS_SERVER_ADDR:localhost:8848}

# springdoc 配置
springdoc:
  swagger-ui:
    path: /doc.html
  packages-to-scan:
    - com.itwray.iw.eat.controller
